Repository dnd-mentee-3rd/dnd-mentee-3rd-1-planto, pull requests merged in 2020-08, with the labels that each got.

#26 Plant 추가
  back-end/package-lock.json
  back-end/package.json
  back-end/src/entity/Plant.ts
  back-end/src/migration/1596207013955-PlantMigration.ts
  back-end/src/migration/1596212463846-PlantDataMigration.ts
Labels: Backend

#29 Backend refactoring
  back-end/README.md
  back-end/app.js
  back-end/bin/www
  back-end/models/index.js
  back-end/public/index.html
  back-end/public/stylesheets/style.css
  back-end/routes/index.js
  back-end/routes/users.js
  back-end/src/controller/UserController.ts
  back-end/src/entity/User.ts
  back-end/src/index.ts
Labels: Backend

#30 테스트 스크립트 TS 포팅
  back-end/example.env
  back-end/jest.config.js
  back-end/package-lock.json
  back-end/package.json
  back-end/tests/database.test.js
  back-end/tests/database.test.ts
Labels: Backend

#35 iOS/Android: 회원가입 View 구현
  front-end/Android/Planto/app/src/main/AndroidManifest.xml
  front-end/Android/Planto/app/src/main/java/com/example/planto/JoinActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/LogInActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/MyApplication.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/PreferenceUtil.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/SplashScreenActivity.kt
  front-end/Android/Planto/app/src/main/res/layout/activity_join.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_log_in.xml
  front-end/Android/Planto/app/src/main/res/values/styles.xml
  front-end/iOS/Planto/Planto.xcodeproj/project.pbxproj
  front-end/iOS/Planto/Planto/Helper/Constants.swift
  front-end/iOS/Planto/Planto/Intro/Base.lproj/Main.storyboard
  front-end/iOS/Planto/Planto/User/JoinViewController.swift
  front-end/iOS/Planto/Planto/User/LogInViewController.swift
  front-end/iOS/Planto/Planto/User/TempUsers.swift
  front-end/iOS/Planto/Planto/User/User.storyboard
  front-end/temp_assets/AppIcons/Assets.xcassets/AppIcon.appiconset/Contents.json
  front-end/temp_assets/AppIcons/android/mipmap-hdpi/ic_launcher.png
  front-end/temp_assets/AppIcons/android/mipmap-mdpi/ic_launcher.png
  front-end/temp_assets/AppIcons/android/mipmap-xhdpi/ic_launcher.png
  front-end/temp_assets/AppIcons/android/mipmap-xxhdpi/ic_launcher.png
  front-end/temp_assets/AppIcons/android/mipmap-xxxhdpi/ic_launcher.png
  front-end/temp_assets/AppIcons/appstore.png
  front-end/temp_assets/AppIcons/playstore.png
  front-end/temp_assets/Plantö_symbol)1024.png
  front-end/temp_assets/TO-OH/TO-OH_1@3x.png
  front-end/temp_assets/TO-OH/TO-OH_2@3x.png
  front-end/temp_assets/TO-OH/TO-OH_3@3x.png
  front-end/temp_assets/TO-OH/TO-OH_4@3x.png
  front-end/temp_assets/TO-OH/TO-OH_5@3x.png
  front-end/temp_assets/TO-OH/TO-OH_6@3x.png
  front-end/temp_assets/TO-OH/TO-OH_7@3x.png
Labels: Android, iOS

#36 iOS/Android: 로그인 View 구현
  front-end/Android/Planto/app/src/main/AndroidManifest.xml
  front-end/Android/Planto/app/src/main/java/com/example/planto/JoinActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/LogInActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/SplashScreenActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/JoinActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/LogInActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/User.kt
  front-end/Android/Planto/app/src/main/res/layout/activity_join.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_log_in.xml
  front-end/Android/Planto/app/src/main/res/values/colors.xml
  front-end/Android/Planto/app/src/main/res/values/intro_strings.xml
  front-end/Android/Planto/app/src/main/res/values/strings.xml
  front-end/Android/Planto/app/src/main/res/values/styles.xml
  front-end/iOS/Planto/Planto.xcodeproj/project.pbxproj
  front-end/iOS/Planto/Planto/Helper/Constants.swift
  front-end/iOS/Planto/Planto/Info.plist
  front-end/iOS/Planto/Planto/User/JoinViewController.swift
  front-end/iOS/Planto/Planto/User/LogInViewController.swift
  front-end/iOS/Planto/Planto/User/TempUsers.swift
  front-end/iOS/Planto/Planto/User/User.storyboard
  front-end/iOS/Planto/Planto/User/User.swift
Labels: Android, Priority: High, iOS

#32 Plant 개선
  back-end/README.md
  back-end/nodemon.json
  back-end/ormconfig.json
  back-end/src/index.ts
  back-end/src/migration/1596207013955-PlantMigration.ts
  back-end/src/migration/1596373829960-PlantMigration.ts
  back-end/src/migration/1596381377796-Plant.ts
  back-end/src/migration/1596382214094-PlantSeed.ts
  back-end/src/routes.ts
  back-end/tests/database.test.ts
Labels: Backend

#39 routes 추가
  back-end/README.md
  back-end/src/index.ts
  back-end/src/routes/plants.ts
  back-end/src/routes/userPlants.ts
Labels: Backend

#40 Android : Add Plant View - 식물 품종 검색 뷰, 검색 결과 뷰, 식물 이름 입력 뷰 추가
  .idea/codeStyles/Project.xml
  .idea/vcs.xml
  front-end/Android/Planto/app/src/main/AndroidManifest.xml
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/AddPlantActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/ConfirmPlantVarietyActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/SearchPlantVarietyActivity.kt
  front-end/Android/Planto/app/src/main/res/layout/activity_add_plant.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_confirm_plant_variety.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_search_plant_variety.xml
  front-end/Android/Planto/app/src/main/res/values/strings.xml
Labels: Android, Priority: High

#43 docs: add CONTRIBUTING
  back-end/CONTRIBUTING.md
Labels: Backend

#47 회원 탈퇴 View 구현
  front-end/Android/Planto/app/src/main/AndroidManifest.xml
  front-end/Android/Planto/app/src/main/java/com/example/planto/SplashScreenActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/LeaveServiceActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/LogInActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/User.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/UserDetailActivity.kt
  front-end/Android/Planto/app/src/main/res/layout/activity_leave_service.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_user_detail.xml
  front-end/iOS/Planto/Planto.xcodeproj/project.pbxproj
  front-end/iOS/Planto/Planto/Info.plist
  front-end/iOS/Planto/Planto/Intro/Base.lproj/Main.storyboard
  front-end/iOS/Planto/Planto/User/JoinViewController.swift
  front-end/iOS/Planto/Planto/User/LeaveServiceViewController.swift
  front-end/iOS/Planto/Planto/User/LogInViewController.swift
  front-end/iOS/Planto/Planto/User/TempUsers.swift
  front-end/iOS/Planto/Planto/User/User.storyboard
  front-end/iOS/Planto/Planto/User/UserDetailViewController.swift
Labels: Android, Priority: Medium, iOS

#48 회원 정보 수정 View 구현
  .gitignore
  front-end/Android/Planto/app/src/main/AndroidManifest.xml
  front-end/Android/Planto/app/src/main/java/com/example/planto/SplashScreenActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/EditProfileActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/JoinActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/LeaveServiceActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/LogInActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/UserDetailActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/UserUtil.kt
  front-end/Android/Planto/app/src/main/res/layout/activity_edit_profile.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_leave_service.xml
  front-end/iOS/Planto/Planto.xcodeproj/project.pbxproj
  front-end/iOS/Planto/Planto/User/EditProfileViewController.swift
  front-end/iOS/Planto/Planto/User/JoinViewController.swift
  front-end/iOS/Planto/Planto/User/LeaveServiceViewController.swift
  front-end/iOS/Planto/Planto/User/LogInViewController.swift
  front-end/iOS/Planto/Planto/User/TempUsers.swift
  front-end/iOS/Planto/Planto/User/User.storyboard
  front-end/iOS/Planto/Planto/User/User.swift
  front-end/iOS/Planto/Planto/User/UserDetailViewController.swift
  front-end/iOS/Planto/Planto/User/UserUtil.swift
Labels: Android, Priority: Medium, iOS

#52 UserPlant 엔드포인트 추가
  back-end/README.md
  back-end/src/entity/UserPlant.ts
  back-end/src/migration/1597148038485-UserPlant.ts
  back-end/src/routes/userPlants.ts
Labels: Backend

#57 User 모델 추가
  back-end/README.md
  back-end/package-lock.json
  back-end/package.json
  back-end/src/entity/User.ts
  back-end/src/entity/UserPlant.ts
  back-end/src/index.ts
  back-end/src/migration/1597148038485-UserPlant.ts
  back-end/src/migration/1597226250955-User.ts
  back-end/src/migration/1597227973214-UserPlant.ts
  back-end/src/routes/plants.ts
  back-end/src/routes/userPlants.ts
  back-end/src/routes/users.ts
Labels: Backend

#58 인증 시스템 구현
  back-end/@types/express.d.ts
  back-end/README.md
  back-end/config/passport.ts
  back-end/package-lock.json
  back-end/package.json
  back-end/src/entity/User.ts
  back-end/src/index.ts
  back-end/src/routes/auth.ts
Labels: Backend

#60 https 적용
  back-end/pm2.json
  back-end/src/index.ts
Labels: Backend

#71 Feature/add plant base layout
  front-end/Android/Planto/app/build.gradle
  front-end/Android/Planto/app/src/main/AndroidManifest.xml
  front-end/Android/Planto/app/src/main/java/com/example/planto/SplashScreenActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/main/MainActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/ConfirmMyPlantActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/ConfirmPlantVarietyActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/GetPlantPictureActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/SearchPlantVarietyActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/myplant/SetPlantNameActivity.kt
  front-end/Android/Planto/app/src/main/res/drawable-v24/watering_can.png
  front-end/Android/Planto/app/src/main/res/drawable-v24/write_diary.png
  front-end/Android/Planto/app/src/main/res/drawable-xxhdpi/cactus.png
  front-end/Android/Planto/app/src/main/res/drawable-xxhdpi/geranium.jpg
  front-end/Android/Planto/app/src/main/res/drawable-xxhdpi/icon_menu.png
  front-end/Android/Planto/app/src/main/res/drawable-xxhdpi/lantana.jpg
  front-end/Android/Planto/app/src/main/res/drawable-xxhdpi/marimo.jpg
  front-end/Android/Planto/app/src/main/res/drawable-xxhdpi/mucho.jpeg
  front-end/Android/Planto/app/src/main/res/drawable-xxhdpi/stucky.jpg
  front-end/Android/Planto/app/src/main/res/drawable/main_plant_variety.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_confirm_my_plant.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_get_plant_picture.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_main.xml
  front-end/Android/Planto/app/src/main/res/layout/activity_set_plant_name.xml
  front-end/Android/Planto/app/src/main/res/values/strings.xml
Labels: Android, Priority: Medium

#62 iOS: Alamofire 적용
  front-end/iOS/Planto/.gitignore
  front-end/iOS/Planto/Planto.xcodeproj/project.pbxproj
  front-end/iOS/Planto/Planto.xcworkspace/contents.xcworkspacedata
  front-end/iOS/Planto/Podfile
  front-end/iOS/Planto/Podfile.lock
Labels: Priority: Low, iOS

#72 Android: User Join
  front-end/Android/Planto/app/src/main/AndroidManifest.xml
  front-end/Android/Planto/app/src/main/java/com/example/planto/SplashScreenActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/helper/Constants.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/helper/RetrofitClient.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/JoinActivity.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/request/Join.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/request/JoinService.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/request/SignIn.kt
  front-end/Android/Planto/app/src/main/java/com/example/planto/user/request/SignInService.kt
  front-end/iOS/Planto/Planto.xcodeproj/project.pbxproj
Labels: Priority: Medium
